### ISSUE TITLE
Disable Kallisto / graph DB to NOT start by default

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/lucyfer#114]
Enable the database to start only if specified on the command line like:

```zsh
./lucy start kallisto
```

The default behavior will be to only start Lucyfer:

```zsh
./lucy start # only starts the Lucyfer dev stuff
```

@phillipross @kinabalu @sbalmos - Thoughts?  Recommendations?  I think there's little to gain from starting Blazegraph as part of the distribution by default.  Going forward, given data volumes, connecting to Neptune might be a better idea.  Thanks!

**Comment by phillipross** [comment]
I agree, better to leave it turned off by default
