### ISSUE TITLE
investigate image size reduction

### ISSUE THREAD

**Issue by phillipross** [pr3d4t0r/lucyfer#124]
There are probably multiple opportunities for reducing the size of the docker images.  Needs ivestigation.

**Comment by pr3d4t0r** [comment]
Per your suggestion, let's start with recommended packages:

I'll throw an `autoremove` after all installation is complete then confirm `/etc/apt/apt.conf.d/99_norecommends` exists in the target build for:

```
APT::Install-Recommends "false";
APT::AutoRemove::RecommendsImportant "false";
APT::AutoRemove::SuggestsImportant "false";
```

Ref:  https://www.debian.org/doc/manuals/aptitude/ch02s05s05.en.html

**Comment by pr3d4t0r** [comment]
Add a version tag to the Lucyfer README.md file, like the one in `poof`, that matches the current release version.

**Comment by phillipross** [comment]
mentioning here for posterity, measures for slimming down include
- adding "--no-install-recommends" switch to apt-get install commands
- adding autoremove and clean commands with apt-get in each RUN line which uses apt-get
- removing /var/lib/apt/lists/* files in each RUN line which uses apt-get
- switching to jre-headless zulu packages since that's all the kotlin notebook needs
