### ISSUE TITLE
BUG:  Lucyfer builds aren't updated to use the latest scipy-notebook build

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/lucyfer#126]
BUG:  Lucyfer builds aren't updated to use the latest scipy-notebook build.

See:

```
jupyter/scipy-notebook   latest    20ed2baa72be   4 months ago   3.89GB
```

Ensure that new builds **ALWAYS** remove the old images and pull the true latest.

**Comment by pr3d4t0r** [comment]
@phillipross suggests pinning it to latest stable reported.

**Comment by pr3d4t0r** [comment]
Fuckers moved to Quay.io - updating the images now quay.io/jupyter/scipy-notebook:latest instead of Docker Hub.  Yuk.

**Comment by phillipross** [comment]
> @phillipross suggests pinning it to latest stable reported.

To clarify, my suggestion is to switch away from using the "latest" tag which is not stable.  It is updated with each new release.  I'm suggesting using the stable tags for more explicit control, stable builds, and predictable updates.
