### ISSUE TITLE
SPARQL notebook unable to render results

### ISSUE THREAD

**Issue by phillipross-numo** [pr3d4t0r/lucyfer#88]
The following shows the image versions:
---
<img width="1291" alt="Screen Shot 2023-01-28 at 10 58 33 AM" src="https://user-images.githubusercontent.com/101197873/215276385-18072ede-eb9a-43f5-8f98-cf1cb3a5f757.png">

The following shows the start of the notebook
---
<img width="1424" alt="Screen Shot 2023-01-28 at 11 01 29 AM" src="https://user-images.githubusercontent.com/101197873/215276490-6ecd8506-abaa-4cb7-b292-efe4d20271cf.png">

The following shows the tabular output of the query first, then the error when asking for the diagram output
---
<img width="1426" alt="Screen Shot 2023-01-28 at 11 02 24 AM" src="https://user-images.githubusercontent.com/101197873/215276520-acafc3c7-3b7b-40ef-8021-ec1435169c64.png">

note the error shown under the cell with the `%display diagram` 
error reads `Error: Response processing error: 'ConjunctiveGraph' object has no attribute 'load'`

**Comment by phillipross-numo** [comment]
graphviz does seem to be installed
---
<img width="938" alt="Screen Shot 2023-01-28 at 11 20 59 AM" src="https://user-images.githubusercontent.com/101197873/215277394-28668d6a-0ac5-4326-a3be-6574886ce1da.png">

**Comment by pr3d4t0r** [comment]
Weird.  Graphviz was supposed to come in the standard distribution.  I will figure out what's changed and why it's missing now.  Will also check with Rook/Wikimedia to see if she removed it from the SPARQL distribution.
