### ISSUE TITLE
Remove the Kotlin kernel and JRE dependencies - if it doesn't get much use

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/lucyfer#90]
Remove the Kotlin kernel and JRE dependencies - if it doesn't get much use.

Request for comments from:

@kinabalu @sbalmos @phillipross

**Comment by phillipross** [comment]
@pr3d4t0r please, keep it for now.  I'll be done some testing of the latest version of the kotlin kernel.
