### ISSUE TITLE
Updated JVM for Kotlin to Java17

### ISSUE THREAD

**Issue by phillipross** [pr3d4t0r/lucyfer#96]
Current jupyterlabs image piggybacks on ubuntu using an old Java version (v11) by default.
Latest version of Java is 19, but latest LTS is 17.
Azul Systems provides a free, opensource, cross-platform distribution of OpenJDK known as Zulu which is a drop-in replacement for Oracle's JVM.

I'll provide a PR to switch from Canonical to Azul's newer version.

**Comment by pr3d4t0r** [comment]
I think both Lucyfer and Kallisto will get this update.

**Comment by phillipross** [comment]
Kallisto, being based on blazegraph, doesn't work with Java versions newer than Java8.
Currently, Kallisto image uses default-jdk from ubuntu, which is Java11, and hasn't been tested much at all.
I've provided PR #96 which updates Lucyfer image to use Azul Zulu Java17, and a similar switch can be done for Kallisto but setting the Java version to 8 instead of 17.
